---
name: Java CI with Maven

on: push


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
  lint: 
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - name: Lint Code Base
      uses: github/super-linter/slim@v4.9.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_ARM: false
        VALIDATE_POWERSHELL: false
        VALIDATE_BASH: false
        VALIDATE_DOCKERFILE_HADOLINT: false
        VALIDATE_DOCKERFILE_JSCPD: false
        VALIDATE_GITHUB_ACTIONS: false
        OUTPUT_DETAILS: detailed
        name: Example workflow for Python using Snyk

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
