---
name: Java CI with Maven

on: push


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        mvn install:install-file -DgroupId="com.socialinfogetter" -DartifactId=SocialInfoGetter -Dversion=0 -Dpackaging=jar -Dfile="src/main/resources/SocialInfoGetter-0.jar"
        mvn idea:idea
        mvn -B package --file pom.xml


  lint: 
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - name: Lint Code Base
      uses: github/super-linter/slim@v4.9.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_JAVA: true
        OUTPUT_DETAILS: detailed


  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - name: Snyk monitor
        run: snyk monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}








